server:
  port: 8081
spring:
  application:
    name: cmq

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd

logging:
  level:
    com.ibm.mq: trace
